// movers-outlook.js — team-change + role outlook overlay for PDATA/PLAYERS.
//
// teamPrev / mover: sourced from pre-2026-09-12 bundled PLAYERS teams
//   (git 47c17da^) with Yahoo/Hashtag abbrev normalization, plus documented
//   priors in docs/adp-additions-2026-09-13.md for add-candidates.
// roleDelta / roleNote: HEURISTIC from Yahoo/Fantrax ADP vs 2025-26 last
//   (per-game) rank — not vacated-usage and not published projections.
// projMpg / projRank: omitted (no Hashtag projection snapshot in repo).
// See docs/movers-outlook.md and scripts/data-provenance/2026-09-20-movers-outlook/.
//
// Generated 2026-09-20. Regenerate: node scripts/data-provenance/2026-09-20-movers-outlook/generate.js
var MOVES={
"AJ Dybantsa":{teamPrev:"WAS",teamCurr:"WAS",mover:false,roleDelta:"unknown"},
"AJ Green":{teamCurr:"MIL",mover:false,roleDelta:"up",roleNote:"ADP ahead of last rank"},
"Aaron Gordon":{teamPrev:"DEN",teamCurr:"DEN",mover:false,roleDelta:"up",roleNote:"ADP ahead of last rank"},
"Aaron Holiday":{teamPrev:"HOU",teamCurr:"HOU",mover:false,roleDelta:"unknown"},
"Aaron Nesmith":{teamPrev:"IND",teamCurr:"IND",mover:false,roleDelta:"up",roleNote:"ADP ahead of last rank"},
"Aaron Wiggins":{teamPrev:"OKC",teamCurr:"ATL",mover:true,roleDelta:"up",roleNote:"OKC→ATL · ADP ahead of last rank"},
"Ace Bailey":{teamPrev:"UTA",teamCurr:"UTA",mover:false,roleDelta:"up",roleNote:"ADP ahead of last rank"},
"Aday Mara":{teamCurr:"OKC",mover:false,roleDelta:"unknown"},
"Adem Bona":{teamPrev:"PHI",teamCurr:"PHI",mover:false,roleDelta:"unknown"},
"Ajay Mitchell":{teamCurr:"OKC",mover:false,roleDelta:"flat"},
"Al Horford":{teamPrev:"BOS",teamCurr:"GS",mover:true,roleDelta:"up",roleNote:"BOS→GS · ADP ahead of last rank"},
"Alex Caruso":{teamPrev:"OKC",teamCurr:"OKC",mover:false,roleDelta:"up",roleNote:"ADP ahead of last rank"},
"Alex Sarr":{teamPrev:"WAS",teamCurr:"WAS",mover:false,roleDelta:"flat"},
"Allen Graves":{teamCurr:"TOR",mover:false,roleDelta:"unknown"},
"Alperen Sengun":{teamPrev:"HOU",teamCurr:"HOU",mover:false,roleDelta:"up",roleNote:"ADP ahead of last rank"},
"Amen Thompson":{teamPrev:"HOU",teamCurr:"HOU",mover:false,roleDelta:"flat"},
"Andre Drummond":{teamPrev:"PHI",teamCurr:"NY",mover:true,roleDelta:"up",roleNote:"PHI→NY · ADP ahead of last rank"},
"Andrew Nembhard":{teamPrev:"IND",teamCurr:"IND",mover:false,roleDelta:"flat"},
"Andrew Wiggins":{teamPrev:"MIA",teamCurr:"MIA",mover:false,roleDelta:"down",roleNote:"ADP behind last rank"},
"Anfernee Simons":{teamPrev:"CHI",teamCurr:"PHI",mover:true,roleDelta:"up",roleNote:"CHI→PHI · ADP ahead of last rank"},
"Anthony Black":{teamPrev:"ORL",teamCurr:"ORL",mover:false,roleDelta:"flat"},
"Anthony Davis":{teamPrev:"WAS",teamCurr:"WAS",mover:false,roleDelta:"flat"},
"Anthony Edwards":{teamPrev:"MIN",teamCurr:"MIN",mover:false,roleDelta:"flat"},
"Ausar Thompson":{teamPrev:"DET",teamCurr:"DET",mover:false,roleDelta:"up",roleNote:"ADP ahead of last rank"},
"Austin Reaves":{teamPrev:"LAL",teamCurr:"LAL",mover:false,roleDelta:"flat"},
"Ayo Dosunmu":{teamPrev:"CHI",teamCurr:"MIN",mover:true,roleDelta:"flat",roleNote:"CHI→MIN · team change; ADP near last rank"},
"Bam Adebayo":{teamPrev:"MIA",teamCurr:"MIA",mover:false,roleDelta:"flat"},
"Bennedict Mathurin":{teamPrev:"IND",teamCurr:"NO",mover:true,roleDelta:"flat",roleNote:"IND→NO · team change; ADP near last rank"},
"Bilal Coulibaly":{teamPrev:"WAS",teamCurr:"WAS",mover:false,roleDelta:"down",roleNote:"ADP behind last rank"},
"Bobby Portis":{teamPrev:"MIL",teamCurr:"MIA",mover:true,roleDelta:"up",roleNote:"MIL→MIA · ADP ahead of last rank"},
"Bogdan Bogdanovic":{teamPrev:"LAC",teamCurr:"HOU",mover:true,roleDelta:"unknown",roleNote:"LAC→HOU · team change; role unclear"},
"Brandin Podziemski":{teamPrev:"GS",teamCurr:"GS",mover:false,roleDelta:"flat"},
"Brandon Ingram":{teamPrev:"TOR",teamCurr:"LAC",mover:true,roleDelta:"flat",roleNote:"TOR→LAC · team change; ADP near last rank"},
"Brandon Miller":{teamPrev:"CHA",teamCurr:"CHA",mover:false,roleDelta:"flat"},
"Brice Sensabaugh":{teamPrev:"UTA",teamCurr:"UTA",mover:false,roleDelta:"down",roleNote:"ADP behind last rank"},
"Brook Lopez":{teamPrev:"LAC",teamCurr:"LAC",mover:false,roleDelta:"up",roleNote:"ADP ahead of last rank"},
"Bub Carrington":{teamPrev:"WAS",teamCurr:"WAS",mover:false,roleDelta:"unknown"},
"Buddy Hield":{teamPrev:"GS",teamCurr:"ATL",mover:true,roleDelta:"unknown",roleNote:"GS→ATL · team change; role unclear"},
"CJ McCollum":{teamPrev:"WAS",teamCurr:"ATL",mover:true,roleDelta:"flat",roleNote:"WAS→ATL · team change; ADP near last rank"},
"Cade Cunningham":{teamPrev:"DET",teamCurr:"DET",mover:false,roleDelta:"flat"},
"Caleb Wilson":{teamCurr:"CHI",mover:false,roleDelta:"unknown"},
"Cam Johnson":{teamPrev:"DEN",teamCurr:"DEN",mover:false,roleDelta:"up",roleNote:"ADP ahead of last rank"},
"Cam Thomas":{teamPrev:"BKN",teamCurr:"BKN",mover:false,roleDelta:"unknown"},
"Cam Whitmore":{teamPrev:"WAS",mover:false,roleDelta:"unknown"},
"Cameron Boozer":{teamCurr:"MEM",mover:false,roleDelta:"unknown"},
"Caris LeVert":{teamPrev:"DET",teamCurr:"MIL",mover:true,roleDelta:"unknown",roleNote:"DET→MIL · team change; role unclear"},
"Cason Wallace":{teamPrev:"OKC",teamCurr:"OKC",mover:false,roleDelta:"flat"},
"Cedric Coward":{teamCurr:"MEM",mover:false,roleDelta:"up",roleNote:"ADP ahead of last rank"},
"Chet Holmgren":{teamPrev:"OKC",teamCurr:"OKC",mover:false,roleDelta:"flat"},
"Christian Braun":{teamCurr:"DEN",mover:false,roleDelta:"up",roleNote:"ADP ahead of last rank"},
"Clint Capela":{teamPrev:"HOU",teamCurr:"HOU",mover:false,roleDelta:"unknown"},
"Coby White":{teamPrev:"CHI",teamCurr:"CHA",mover:true,roleDelta:"up",roleNote:"CHI→CHA · ADP ahead of last rank"},
"Collin Gillespie":{teamPrev:"PHO",teamCurr:"PHO",mover:false,roleDelta:"down",roleNote:"ADP behind last rank"},
"Collin Murray-Boyles":{teamPrev:"TOR",teamCurr:"TOR",mover:false,roleDelta:"up",roleNote:"ADP ahead of last rank"},
"Collin Sexton":{teamPrev:"UTA",teamCurr:"LAL",mover:true,roleDelta:"up",roleNote:"UTA→LAL · ADP ahead of last rank"},
"Cooper Flagg":{teamPrev:"DAL",teamCurr:"DAL",mover:false,roleDelta:"up",roleNote:"ADP ahead of last rank"},
"D'Angelo Russell":{teamPrev:"DAL",teamCurr:"DAL",mover:false,roleDelta:"unknown"},
"Damian Lillard":{teamPrev:"MIL",teamCurr:"POR",mover:true,roleDelta:"unknown",roleNote:"MIL→POR · team change; role unclear"},
"Daniel Gafford":{teamPrev:"DAL",teamCurr:"DAL",mover:false,roleDelta:"up",roleNote:"ADP ahead of last rank"},
"Darius Acuff Jr.":{teamCurr:"SAC",mover:false,roleDelta:"unknown"},
"Darius Garland":{teamPrev:"LAC",teamCurr:"LAC",mover:false,roleDelta:"flat"},
"Darryn Peterson":{teamCurr:"UTA",mover:false,roleDelta:"unknown"},
"Davion Mitchell":{teamPrev:"MIA",teamCurr:"MIA",mover:false,roleDelta:"up",roleNote:"ADP ahead of last rank"},
"Day'Ron Sharpe":{teamCurr:"BKN",mover:false,roleDelta:"up",roleNote:"ADP ahead of last rank"},
"De'Aaron Fox":{teamPrev:"SA",teamCurr:"SA",mover:false,roleDelta:"flat"},
"De'Andre Hunter":{teamPrev:"CLE",teamCurr:"SAC",mover:true,roleDelta:"unknown",roleNote:"CLE→SAC · team change; role unclear"},
"DeMar DeRozan":{teamPrev:"SAC",teamCurr:"DEN",mover:true,roleDelta:"down",roleNote:"SAC→DEN · ADP behind last rank"},
"Deandre Ayton":{teamPrev:"LAL",teamCurr:"WAS",mover:true,roleDelta:"down",roleNote:"LAL→WAS · ADP behind last rank"},
"Dejounte Murray":{teamPrev:"NO",teamCurr:"NO",mover:false,roleDelta:"flat"},
"Deni Avdija":{teamPrev:"POR",teamCurr:"POR",mover:false,roleDelta:"flat"},
"Dennis Schroder":{teamPrev:"SAC",teamCurr:"CHA",mover:true,roleDelta:"up",roleNote:"SAC→CHA · ADP ahead of last rank"},
"Dereck Lively II":{teamPrev:"DAL",teamCurr:"DAL",mover:false,roleDelta:"flat"},
"Derik Queen":{teamCurr:"NO",mover:false,roleDelta:"up",roleNote:"ADP ahead of last rank"},
"Derrick Jones Jr.":{teamPrev:"LAC",teamCurr:"LAC",mover:false,roleDelta:"down",roleNote:"ADP behind last rank"},
"Derrick White":{teamPrev:"BOS",teamCurr:"BOS",mover:false,roleDelta:"flat"},
"Desmond Bane":{teamPrev:"ORL",teamCurr:"ORL",mover:false,roleDelta:"flat"},
"Devin Booker":{teamPrev:"PHO",teamCurr:"PHO",mover:false,roleDelta:"flat"},
"Devin Carter":{teamPrev:"SAC",teamCurr:"ATL",mover:true,roleDelta:"unknown",roleNote:"SAC→ATL · team change; role unclear"},
"Devin Vassell":{teamPrev:"SA",teamCurr:"SA",mover:false,roleDelta:"flat"},
"Dillon Brooks":{teamPrev:"PHO",teamCurr:"PHO",mover:false,roleDelta:"up",roleNote:"ADP ahead of last rank"},
"Domantas Sabonis":{teamPrev:"SAC",teamCurr:"SAC",mover:false,roleDelta:"up",roleNote:"ADP ahead of last rank"},
"Donovan Clingan":{teamPrev:"POR",teamCurr:"POR",mover:false,roleDelta:"flat"},
"Donovan Mitchell":{teamPrev:"CLE",teamCurr:"CLE",mover:false,roleDelta:"flat"},
"Donte DiVincenzo":{teamPrev:"MIN",teamCurr:"MIN",mover:false,roleDelta:"unknown"},
"Dorian Finney-Smith":{teamPrev:"HOU",teamCurr:"CHA",mover:true,roleDelta:"unknown",roleNote:"HOU→CHA · team change; role unclear"},
"Draymond Green":{teamCurr:"GS",mover:false,roleDelta:"up",roleNote:"ADP ahead of last rank"},
"Duncan Robinson":{teamPrev:"MIA",teamCurr:"DET",mover:true,roleDelta:"up",roleNote:"MIA→DET · ADP ahead of last rank"},
"Dylan Harper":{teamPrev:"SA",teamCurr:"SA",mover:false,roleDelta:"up",roleNote:"ADP ahead of last rank"},
"Dyson Daniels":{teamPrev:"ATL",teamCurr:"ATL",mover:false,roleDelta:"flat"},
"Egor Demin":{teamCurr:"BKN",mover:false,roleDelta:"up",roleNote:"ADP ahead of last rank"},
"Evan Mobley":{teamPrev:"CLE",teamCurr:"CLE",mover:false,roleDelta:"up",roleNote:"ADP ahead of last rank"},
"Franz Wagner":{teamPrev:"ORL",teamCurr:"ORL",mover:false,roleDelta:"up",roleNote:"ADP ahead of last rank"},
"Fred VanVleet":{teamPrev:"HOU",teamCurr:"HOU",mover:false,roleDelta:"unknown"},
"GG Jackson":{teamPrev:"MEM",teamCurr:"MEM",mover:false,roleDelta:"up",roleNote:"ADP ahead of last rank"},
"Giannis Antetokounmpo":{teamPrev:"MIL",teamCurr:"MIA",mover:true,roleDelta:"up",roleNote:"MIL→MIA · ADP ahead of last rank"},
"Goga Bitadze":{teamPrev:"ORL",teamCurr:"ORL",mover:false,roleDelta:"unknown"},
"Gradey Dick":{teamPrev:"TOR",teamCurr:"LAC",mover:true,roleDelta:"unknown",roleNote:"TOR→LAC · team change; role unclear"},
"Grayson Allen":{teamPrev:"PHO",teamCurr:"CHA",mover:true,roleDelta:"down",roleNote:"PHO→CHA · ADP behind last rank"},
"Harrison Barnes":{teamPrev:"SA",teamCurr:"SA",mover:false,roleDelta:"flat"},
"Haywood Highsmith":{teamPrev:"MIA",teamCurr:"MIA",mover:false,roleDelta:"unknown"},
"Herbert Jones":{teamPrev:"NO",teamCurr:"NO",mover:false,roleDelta:"down",roleNote:"ADP behind last rank"},
"Immanuel Quickley":{teamPrev:"TOR",teamCurr:"TOR",mover:false,roleDelta:"down",roleNote:"ADP behind last rank"},
"Isaiah Collier":{teamPrev:"UTA",teamCurr:"UTA",mover:false,roleDelta:"up",roleNote:"ADP ahead of last rank"},
"Isaiah Hartenstein":{teamPrev:"OKC",teamCurr:"OKC",mover:false,roleDelta:"flat"},
"Isaiah Joe":{teamPrev:"OKC",teamCurr:"DET",mover:true,roleDelta:"down",roleNote:"OKC→DET · ADP behind last rank"},
"Isaiah Stewart":{teamPrev:"DET",teamCurr:"MEM",mover:true,roleDelta:"up",roleNote:"DET→MEM · ADP ahead of last rank"},
"Ivica Zubac":{teamPrev:"LAC",teamCurr:"IND",mover:true,roleDelta:"up",roleNote:"LAC→IND · ADP ahead of last rank"},
"Ja Morant":{teamPrev:"MEM",teamCurr:"POR",mover:true,roleDelta:"up",roleNote:"MEM→POR · ADP ahead of last rank"},
"Ja'Kobe Walter":{teamPrev:"TOR",teamCurr:"TOR",mover:false,roleDelta:"flat"},
"Jabari Smith Jr.":{teamPrev:"HOU",teamCurr:"HOU",mover:false,roleDelta:"flat"},
"Jaden Ivey":{teamPrev:"DET",teamCurr:"DET",mover:false,roleDelta:"unknown"},
"Jaden McDaniels":{teamCurr:"MIN",mover:false,roleDelta:"flat"},
"Jaime Jaquez Jr.":{teamPrev:"MIA",teamCurr:"MIL",mover:true,roleDelta:"up",roleNote:"MIA→MIL · ADP ahead of last rank"},
"Jakob Poeltl":{teamPrev:"TOR",teamCurr:"TOR",mover:false,roleDelta:"flat"},
"Jalen Brunson":{teamPrev:"NY",teamCurr:"NY",mover:false,roleDelta:"flat"},
"Jalen Duren":{teamPrev:"DET",teamCurr:"DET",mover:false,roleDelta:"flat"},
"Jalen Green":{teamPrev:"PHO",teamCurr:"PHO",mover:false,roleDelta:"up",roleNote:"ADP ahead of last rank"},
"Jalen Johnson":{teamPrev:"ATL",teamCurr:"ATL",mover:false,roleDelta:"flat"},
"Jalen Smith":{teamPrev:"CHI",teamCurr:"CHI",mover:false,roleDelta:"down",roleNote:"ADP behind last rank"},
"Jalen Suggs":{teamPrev:"ORL",teamCurr:"ORL",mover:false,roleDelta:"down",roleNote:"ADP behind last rank"},
"Jalen Williams":{teamPrev:"OKC",teamCurr:"OKC",mover:false,roleDelta:"up",roleNote:"ADP ahead of last rank"},
"Jamal Murray":{teamPrev:"DEN",teamCurr:"DEN",mover:false,roleDelta:"flat"},
"Jamal Shead":{teamPrev:"TOR",teamCurr:"TOR",mover:false,roleDelta:"up",roleNote:"ADP ahead of last rank"},
"James Harden":{teamPrev:"CLE",teamCurr:"CLE",mover:false,roleDelta:"down",roleNote:"ADP behind last rank"},
"Jared McCain":{teamPrev:"PHI",teamCurr:"OKC",mover:true,roleDelta:"up",roleNote:"PHI→OKC · ADP ahead of last rank"},
"Jaren Jackson Jr.":{teamPrev:"UTA",teamCurr:"UTA",mover:false,roleDelta:"flat"},
"Jarred Vanderbilt":{teamPrev:"LAL",teamCurr:"LAL",mover:false,roleDelta:"unknown"},
"Jarrett Allen":{teamPrev:"CLE",teamCurr:"CLE",mover:false,roleDelta:"flat"},
"Jay Huff":{teamPrev:"IND",teamCurr:"IND",mover:false,roleDelta:"flat"},
"Jaylen Brown":{teamPrev:"BOS",teamCurr:"PHI",mover:true,roleDelta:"flat",roleNote:"BOS→PHI · team change; ADP near last rank"},
"Jaylen Wells":{teamPrev:"MEM",teamCurr:"MEM",mover:false,roleDelta:"flat"},
"Jayson Tatum":{teamPrev:"BOS",teamCurr:"BOS",mover:false,roleDelta:"flat"},
"Jerami Grant":{teamPrev:"POR",teamCurr:"MEM",mover:true,roleDelta:"down",roleNote:"POR→MEM · ADP behind last rank"},
"Jeremiah Fears":{teamPrev:"NO",teamCurr:"NO",mover:false,roleDelta:"up",roleNote:"ADP ahead of last rank"},
"Jeremy Sochan":{teamPrev:"SA",teamCurr:"POR",mover:true,roleDelta:"unknown",roleNote:"SA→POR · team change; role unclear"},
"Jimmy Butler":{teamPrev:"GS",teamCurr:"GS",mover:false,roleDelta:"down",roleNote:"ADP behind last rank"},
"Joel Embiid":{teamPrev:"PHI",teamCurr:"PHI",mover:false,roleDelta:"down",roleNote:"ADP behind last rank"},
"John Collins":{teamPrev:"LAC",teamCurr:"DET",mover:true,roleDelta:"flat",roleNote:"LAC→DET · team change; ADP near last rank"},
"Jonas Valanciunas":{teamPrev:"DEN",teamCurr:"DEN",mover:false,roleDelta:"unknown"},
"Jonathan Isaac":{teamPrev:"ORL",teamCurr:"ORL",mover:false,roleDelta:"unknown"},
"Jonathan Kuminga":{teamPrev:"GS",teamCurr:"MIN",mover:true,roleDelta:"up",roleNote:"GS→MIN · ADP ahead of last rank"},
"Jonathan Mogbo":{teamPrev:"TOR",teamCurr:"TOR",mover:false,roleDelta:"unknown"},
"Jordan Clarkson":{teamPrev:"NY",teamCurr:"NY",mover:false,roleDelta:"unknown"},
"Jose Alvarado":{teamPrev:"NO",teamCurr:"NY",mover:true,roleDelta:"unknown",roleNote:"NO→NY · team change; role unclear"},
"Josh Giddey":{teamPrev:"CHI",teamCurr:"CHI",mover:false,roleDelta:"flat"},
"Josh Hart":{teamPrev:"NY",teamCurr:"NY",mover:false,roleDelta:"flat"},
"Jrue Holiday":{teamPrev:"BOS",teamCurr:"POR",mover:true,roleDelta:"flat",roleNote:"BOS→POR · team change; ADP near last rank"},
"Julian Champagnie":{teamCurr:"SA",mover:false,roleDelta:"flat"},
"Julius Randle":{teamPrev:"MIN",teamCurr:"BKN",mover:true,roleDelta:"up",roleNote:"MIN→BKN · ADP ahead of last rank"},
"Jusuf Nurkic":{teamPrev:"UTA",teamCurr:"UTA",mover:false,roleDelta:"flat"},
"Karl-Anthony Towns":{teamPrev:"NY",teamCurr:"NY",mover:false,roleDelta:"flat"},
"Kawhi Leonard":{teamPrev:"LAC",teamCurr:"TOR",mover:true,roleDelta:"down",roleNote:"LAC→TOR · ADP behind last rank"},
"Keaton Wagler":{teamCurr:"LAC",mover:false,roleDelta:"unknown"},
"Keegan Murray":{teamPrev:"SAC",teamCurr:"SAC",mover:false,roleDelta:"down",roleNote:"ADP behind last rank"},
"Kel'el Ware":{teamPrev:"MIA",teamCurr:"MIL",mover:true,roleDelta:"down",roleNote:"MIA→MIL · ADP behind last rank"},
"Keldon Johnson":{teamPrev:"SA",teamCurr:"SA",mover:false,roleDelta:"down",roleNote:"ADP behind last rank"},
"Kelly Oubre Jr.":{teamPrev:"PHI",teamCurr:"IND",mover:true,roleDelta:"flat",roleNote:"PHI→IND · team change; ADP near last rank"},
"Kenrich Williams":{teamPrev:"OKC",teamCurr:"OKC",mover:false,roleDelta:"unknown"},
"Keon Ellis":{teamPrev:"SAC",teamCurr:"BKN",mover:true,roleDelta:"flat",roleNote:"SAC→BKN · team change; ADP near last rank"},
"Kevin Durant":{teamPrev:"HOU",teamCurr:"HOU",mover:false,roleDelta:"flat"},
"Kevin Porter Jr.":{teamCurr:"MIL",mover:false,roleDelta:"down",roleNote:"ADP behind last rank"},
"Kevon Looney":{teamPrev:"NO",teamCurr:"LAL",mover:true,roleDelta:"unknown",roleNote:"NO→LAL · team change; role unclear"},
"Keyonte George":{teamPrev:"UTA",teamCurr:"UTA",mover:false,roleDelta:"down",roleNote:"ADP behind last rank"},
"Khaman Maluach":{teamCurr:"PHO",mover:false,roleDelta:"up",roleNote:"ADP ahead of last rank"},
"Khris Middleton":{teamPrev:"WAS",teamCurr:"WAS",mover:false,roleDelta:"up",roleNote:"ADP ahead of last rank"},
"Kingston Flemings":{teamCurr:"ATL",mover:false,roleDelta:"unknown"},
"Klay Thompson":{teamPrev:"DAL",teamCurr:"MIA",mover:true,roleDelta:"up",roleNote:"DAL→MIA · ADP ahead of last rank"},
"Kon Knueppel":{teamPrev:"CHA",teamCurr:"CHA",mover:false,roleDelta:"up",roleNote:"ADP ahead of last rank"},
"Kristaps Porzingis":{teamPrev:"ATL",teamCurr:"GS",mover:true,roleDelta:"down",roleNote:"ATL→GS · ADP behind last rank"},
"Kyle Filipowski":{teamPrev:"UTA",teamCurr:"UTA",mover:false,roleDelta:"up",roleNote:"ADP ahead of last rank"},
"Kyle Kuzma":{teamPrev:"MIL",teamCurr:"MIL",mover:false,roleDelta:"up",roleNote:"ADP ahead of last rank"},
"Kyrie Irving":{teamPrev:"DAL",teamCurr:"DAL",mover:false,roleDelta:"unknown"},
"Kyshawn George":{teamPrev:"WAS",teamCurr:"WAS",mover:false,roleDelta:"down",roleNote:"ADP behind last rank"},
"LaMelo Ball":{teamPrev:"CHA",teamCurr:"MIN",mover:true,roleDelta:"up",roleNote:"CHA→MIN · ADP ahead of last rank"},
"Lauri Markkanen":{teamPrev:"UTA",teamCurr:"UTA",mover:false,roleDelta:"down",roleNote:"ADP behind last rank"},
"LeBron James":{teamPrev:"LAL",teamCurr:"PHI",mover:true,roleDelta:"flat",roleNote:"LAL→PHI · team change; ADP near last rank"},
"Leonard Miller":{teamPrev:"MIN",teamCurr:"CHI",mover:true,roleDelta:"up",roleNote:"MIN→CHI · ADP ahead of last rank"},
"Luguentz Dort":{teamPrev:"OKC",teamCurr:"ATL",mover:true,roleDelta:"up",roleNote:"OKC→ATL · ADP ahead of last rank"},
"Luka Doncic":{teamPrev:"LAL",teamCurr:"LAL",mover:false,roleDelta:"flat"},
"Luke Kennard":{teamPrev:"LAL",teamCurr:"PHO",mover:true,roleDelta:"up",roleNote:"LAL→PHO · ADP ahead of last rank"},
"Luke Kornet":{teamPrev:"BOS",teamCurr:"SA",mover:true,roleDelta:"up",roleNote:"BOS→SA · ADP ahead of last rank"},
"Malik Monk":{teamPrev:"SAC",teamCurr:"SAC",mover:false,roleDelta:"flat"},
"Mark Williams":{teamPrev:"PHO",teamCurr:"PHO",mover:false,roleDelta:"down",roleNote:"ADP behind last rank"},
"Matas Buzelis":{teamPrev:"CHI",teamCurr:"CHI",mover:false,roleDelta:"flat"},
"Max Christie":{teamPrev:"DAL",teamCurr:"DAL",mover:false,roleDelta:"down",roleNote:"ADP behind last rank"},
"Maxime Raynaud":{teamPrev:"SAC",teamCurr:"SAC",mover:false,roleDelta:"up",roleNote:"ADP ahead of last rank"},
"Michael Porter Jr.":{teamPrev:"BKN",teamCurr:"BKN",mover:false,roleDelta:"down",roleNote:"ADP behind last rank"},
"Mikal Bridges":{teamPrev:"NY",teamCurr:"NY",mover:false,roleDelta:"flat"},
"Mike Conley":{teamPrev:"MIN",teamCurr:"BOS",mover:true,roleDelta:"unknown",roleNote:"MIN→BOS · team change; role unclear"},
"Mikel Brown Jr.":{teamCurr:"BKN",mover:false,roleDelta:"unknown"},
"Miles Bridges":{teamPrev:"CHA",teamCurr:"PHO",mover:true,roleDelta:"flat",roleNote:"CHA→PHO · team change; ADP near last rank"},
"Miles McBride":{teamPrev:"NY",teamCurr:"NY",mover:false,roleDelta:"down",roleNote:"ADP behind last rank"},
"Mitchell Robinson":{teamPrev:"NY",teamCurr:"BOS",mover:true,roleDelta:"up",roleNote:"NY→BOS · ADP ahead of last rank"},
"Morez Johnson Jr.":{teamCurr:"DAL",mover:false,roleDelta:"unknown"},
"Moses Moody":{teamPrev:"GS",teamCurr:"GS",mover:false,roleDelta:"unknown"},
"Moussa Diabate":{teamCurr:"CHA",mover:false,roleDelta:"up",roleNote:"ADP ahead of last rank"},
"Myles Turner":{teamPrev:"MIL",teamCurr:"MIL",mover:false,roleDelta:"flat"},
"Naji Marshall":{teamPrev:"DAL",teamCurr:"DAL",mover:false,roleDelta:"down",roleNote:"ADP behind last rank"},
"Nate Ament":{teamCurr:"MIL",mover:false,roleDelta:"unknown"},
"Naz Reid":{teamPrev:"MIN",teamCurr:"CHA",mover:true,roleDelta:"up",roleNote:"MIN→CHA · ADP ahead of last rank"},
"Neemias Queta":{teamPrev:"BOS",teamCurr:"BOS",mover:false,roleDelta:"down",roleNote:"ADP behind last rank"},
"Nic Claxton":{teamPrev:"BKN",teamCurr:"CHI",mover:true,roleDelta:"up",roleNote:"BKN→CHI · ADP ahead of last rank"},
"Nickeil Alexander-Walker":{teamPrev:"ATL",teamCurr:"ATL",mover:false,roleDelta:"down",roleNote:"ADP behind last rank"},
"Nicolas Batum":{teamPrev:"LAC",teamCurr:"LAC",mover:false,roleDelta:"unknown"},
"Nikola Jokic":{teamPrev:"DEN",teamCurr:"DEN",mover:false,roleDelta:"flat"},
"Nikola Jovic":{teamPrev:"MIA",teamCurr:"MIA",mover:false,roleDelta:"unknown"},
"Nikola Vucevic":{teamPrev:"BOS",teamCurr:"BOS",mover:false,roleDelta:"down",roleNote:"ADP behind last rank"},
"Norman Powell":{teamPrev:"MIA",teamCurr:"CHI",mover:true,roleDelta:"down",roleNote:"MIA→CHI · ADP behind last rank"},
"OG Anunoby":{teamPrev:"NY",teamCurr:"NY",mover:false,roleDelta:"down",roleNote:"ADP behind last rank"},
"Obi Toppin":{teamPrev:"IND",teamCurr:"IND",mover:false,roleDelta:"down",roleNote:"ADP behind last rank"},
"Ochai Agbaji":{teamPrev:"TOR",teamCurr:"TOR",mover:false,roleDelta:"unknown"},
"Onyeka Okongwu":{teamPrev:"ATL",teamCurr:"ATL",mover:false,roleDelta:"flat"},
"P.J. Washington":{teamPrev:"DAL",teamCurr:"DAL",mover:false,roleDelta:"up",roleNote:"ADP ahead of last rank"},
"Paolo Banchero":{teamPrev:"ORL",teamCurr:"ORL",mover:false,roleDelta:"up",roleNote:"ADP ahead of last rank"},
"Pascal Siakam":{teamPrev:"IND",teamCurr:"IND",mover:false,roleDelta:"up",roleNote:"ADP ahead of last rank"},
"Paul George":{teamPrev:"PHI",teamCurr:"BOS",mover:true,roleDelta:"down",roleNote:"PHI→BOS · ADP behind last rank"},
"Paul Reed":{teamCurr:"DET",mover:false,roleDelta:"up",roleNote:"ADP ahead of last rank"},
"Payton Pritchard":{teamPrev:"BOS",teamCurr:"BOS",mover:false,roleDelta:"flat"},
"Pelle Larsson":{teamPrev:"MIA",teamCurr:"MIA",mover:false,roleDelta:"up",roleNote:"ADP ahead of last rank"},
"Peyton Watson":{teamPrev:"DEN",teamCurr:"CLE",mover:true,roleDelta:"flat",roleNote:"DEN→CLE · team change; ADP near last rank"},
"Quentin Grimes":{teamPrev:"PHI",teamCurr:"LAL",mover:true,roleDelta:"up",roleNote:"PHI→LAL · ADP ahead of last rank"},
"RJ Barrett":{teamPrev:"TOR",teamCurr:"TOR",mover:false,roleDelta:"up",roleNote:"ADP ahead of last rank"},
"Reed Sheppard":{teamPrev:"HOU",teamCurr:"HOU",mover:false,roleDelta:"down",roleNote:"ADP behind last rank"},
"Rob Dillingham":{teamPrev:"MIN",teamCurr:"CHI",mover:true,roleDelta:"unknown",roleNote:"MIN→CHI · team change; role unclear"},
"Ron Holland":{teamPrev:"DET",teamCurr:"DET",mover:false,roleDelta:"up",roleNote:"ADP ahead of last rank"},
"Royce O'Neale":{teamPrev:"PHO",teamCurr:"CHA",mover:true,roleDelta:"down",roleNote:"PHO→CHA · ADP behind last rank"},
"Rudy Gobert":{teamPrev:"MIN",teamCurr:"MIN",mover:false,roleDelta:"flat"},
"Rui Hachimura":{teamPrev:"LAL",teamCurr:"LAC",mover:true,roleDelta:"up",roleNote:"LAL→LAC · ADP ahead of last rank"},
"Ryan Kalkbrenner":{teamCurr:"CHA",mover:false,roleDelta:"up",roleNote:"ADP ahead of last rank"},
"Ryan Rollins":{teamPrev:"MIL",teamCurr:"MIL",mover:false,roleDelta:"down",roleNote:"ADP behind last rank"},
"Saddiq Bey":{teamPrev:"NO",teamCurr:"NO",mover:false,roleDelta:"down",roleNote:"ADP behind last rank"},
"Sam Hauser":{teamCurr:"BOS",mover:false,roleDelta:"up",roleNote:"ADP ahead of last rank"},
"Sam Merrill":{teamPrev:"CLE",teamCurr:"CLE",mover:false,roleDelta:"down",roleNote:"ADP behind last rank"},
"Sandro Mamukelashvili":{teamPrev:"TOR",teamCurr:"LAL",mover:true,roleDelta:"up",roleNote:"TOR→LAL · ADP ahead of last rank"},
"Santi Aldama":{teamPrev:"MEM",teamCurr:"DAL",mover:true,roleDelta:"down",roleNote:"MEM→DAL · ADP behind last rank"},
"Scoot Henderson":{teamPrev:"POR",teamCurr:"POR",mover:false,roleDelta:"up",roleNote:"ADP ahead of last rank"},
"Scottie Barnes":{teamPrev:"TOR",teamCurr:"TOR",mover:false,roleDelta:"flat"},
"Scotty Pippen Jr.":{teamPrev:"MEM",teamCurr:"MEM",mover:false,roleDelta:"flat"},
"Shaedon Sharpe":{teamPrev:"POR",teamCurr:"POR",mover:false,roleDelta:"flat"},
"Shai Gilgeous-Alexander":{teamPrev:"OKC",teamCurr:"OKC",mover:false,roleDelta:"flat"},
"Stephen Curry":{teamPrev:"GS",teamCurr:"GS",mover:false,roleDelta:"flat"},
"Stephon Castle":{teamPrev:"SA",teamCurr:"SA",mover:false,roleDelta:"up",roleNote:"ADP ahead of last rank"},
"Steven Adams":{teamPrev:"HOU",teamCurr:"HOU",mover:false,roleDelta:"up",roleNote:"ADP ahead of last rank"},
"T.J. McConnell":{teamPrev:"IND",teamCurr:"IND",mover:false,roleDelta:"up",roleNote:"ADP ahead of last rank"},
"Tari Eason":{teamPrev:"HOU",teamCurr:"HOU",mover:false,roleDelta:"up",roleNote:"ADP ahead of last rank"},
"Taurean Prince":{teamPrev:"MIL",teamCurr:"MIL",mover:false,roleDelta:"unknown"},
"Taylor Hendricks":{teamPrev:"UTA",teamCurr:"MEM",mover:true,roleDelta:"up",roleNote:"UTA→MEM · ADP ahead of last rank"},
"Thomas Bryant":{teamPrev:"CLE",teamCurr:"CLE",mover:false,roleDelta:"unknown"},
"Tobias Harris":{teamPrev:"DET",teamCurr:"SA",mover:true,roleDelta:"down",roleNote:"DET→SA · ADP behind last rank"},
"Toumani Camara":{teamPrev:"POR",teamCurr:"POR",mover:false,roleDelta:"flat"},
"Trae Young":{teamPrev:"WAS",teamCurr:"WAS",mover:false,roleDelta:"up",roleNote:"ADP ahead of last rank"},
"Tre Jones":{teamPrev:"CHI",teamCurr:"CHI",mover:false,roleDelta:"down",roleNote:"ADP behind last rank"},
"Trey Murphy III":{teamPrev:"NO",teamCurr:"NO",mover:false,roleDelta:"flat"},
"Tristan Vukcevic":{teamPrev:"WAS",teamCurr:"WAS",mover:false,roleDelta:"unknown"},
"Tristan da Silva":{teamPrev:"ORL",teamCurr:"ORL",mover:false,roleDelta:"down",roleNote:"ADP behind last rank"},
"Ty Jerome":{teamPrev:"CLE",teamCurr:"MEM",mover:true,roleDelta:"down",roleNote:"CLE→MEM · ADP behind last rank"},
"Tyler Herro":{teamPrev:"MIA",teamCurr:"MIL",mover:true,roleDelta:"down",roleNote:"MIA→MIL · ADP behind last rank"},
"Tyrese Haliburton":{teamPrev:"IND",teamCurr:"IND",mover:false,roleDelta:"unknown"},
"Tyrese Maxey":{teamPrev:"PHI",teamCurr:"PHI",mover:false,roleDelta:"flat"},
"VJ Edgecombe":{teamPrev:"PHI",teamCurr:"PHI",mover:false,roleDelta:"flat"},
"Victor Wembanyama":{teamPrev:"SA",teamCurr:"SA",mover:false,roleDelta:"flat"},
"Walker Kessler":{teamPrev:"LAL",teamCurr:"LAL",mover:false,roleDelta:"flat"},
"Walter Clayton Jr.":{teamPrev:"UTA",teamCurr:"MEM",mover:true,roleDelta:"unknown",roleNote:"UTA→MEM · team change; role unclear"},
"Wendell Carter Jr.":{teamPrev:"ORL",teamCurr:"ORL",mover:false,roleDelta:"flat"},
"Yang Hansen":{teamPrev:"POR",teamCurr:"POR",mover:false,roleDelta:"unknown"},
"Yaxel Lendeborg":{teamCurr:"GS",mover:false,roleDelta:"unknown"},
"Yves Missi":{teamPrev:"NO",teamCurr:"NO",mover:false,roleDelta:"up",roleNote:"ADP ahead of last rank"},
"Zach Edey":{teamPrev:"MEM",teamCurr:"MEM",mover:false,roleDelta:"unknown"},
"Zach LaVine":{teamPrev:"SAC",teamCurr:"SAC",mover:false,roleDelta:"down",roleNote:"ADP behind last rank"},
"Zion Williamson":{teamPrev:"NO",teamCurr:"NO",mover:false,roleDelta:"up",roleNote:"ADP ahead of last rank"}
};
(function(){
  if(typeof PDATA==="undefined")return;
  Object.keys(MOVES).forEach(function(n){
    if(!Object.prototype.hasOwnProperty.call(PDATA,n))return;
    var m=MOVES[n],d=PDATA[n];
    if(m.teamPrev!=null)d.teamPrev=m.teamPrev;
    if(m.teamCurr!=null)d.teamCurr=m.teamCurr;
    d.mover=!!m.mover;
    d.roleDelta=m.roleDelta||"unknown";
    if(m.roleNote)d.roleNote=m.roleNote;
  });
})();
