/* Draft Lab player pool: built-in rank order, positions, teams, merged with
   player-data.js (ADP, ranks, injuries, movers) and category strength tags.
   Loaded after player-data.js / movers-outlook.js / vacated-usage.js. Globals: PLAYERS, CATS.
   The PLAYERS order IS the built-in Rank and is generated, not curated: run
   `node scripts/rebuild-rank.js` after any ADP or injury refresh (consensus ADP
   nudged toward 2025-26 production; formula in that script). test-rank-order.js
   fails when the order is stale. */
var PLAYERS=[
["Nikola Jokic",['C'],"DEN"],["Victor Wembanyama",['C'],"SA"],["Shai Gilgeous-Alexander",['PG'],"OKC"],
["Luka Doncic",['PG', 'SG'],"LAL"],["Tyrese Maxey",['PG'],"PHI"],["Cade Cunningham",['PG', 'SG'],"DET"],
["Donovan Mitchell",['SG', 'PG'],"CLE"],["Scottie Barnes",['SF', 'PF', 'C'],"TOR"],["Kevin Durant",['SG', 'SF', 'PF'],"HOU"],
["Anthony Edwards",['PG', 'SG'],"MIN"],["Jalen Johnson",['SF', 'PF'],"ATL"],["Tyrese Haliburton",['PG', 'SG'],"IND"],
["Jamal Murray",['PG'],"DEN"],["Karl-Anthony Towns",['C', 'PF'],"NY"],["Cooper Flagg",['SG', 'SF', 'PF'],"DAL"],
["Kawhi Leonard",['SG', 'SF', 'PF'],"TOR"],["Amen Thompson",['PG', 'SG'],"HOU"],["Chet Holmgren",['C', 'PF'],"OKC"],
["James Harden",['PG', 'SG'],"CLE"],["Giannis Antetokounmpo",['PF', 'C'],"MIA"],["Jayson Tatum",['PF', 'SF'],"BOS"],
["Trey Murphy III",['SF', 'SG'],"NO"],["Jalen Brunson",['PG'],"NY"],["Stephen Curry",['PG'],"GS"],
["Alperen Sengun",['PF', 'C'],"HOU"],["Austin Reaves",['SG', 'PG', 'SF'],"LAL"],["LaMelo Ball",['PG'],"MIN"],
["Bam Adebayo",['C', 'PF'],"MIA"],["Devin Booker",['PG', 'SG'],"PHO"],["Derrick White",['PG', 'SG'],"BOS"],
["Jalen Duren",['C'],"DET"],["Jaylen Brown",['SG', 'SF', 'PF'],"PHI"],["Donovan Clingan",['C'],"POR"],
["Lauri Markkanen",['PF', 'SF'],"UTA"],["Desmond Bane",['SG', 'SF'],"ORL"],["Evan Mobley",['PF', 'C'],"CLE"],
["Nickeil Alexander-Walker",['PG', 'SG'],"ATL"],["Josh Giddey",['PG', 'SG'],"CHI"],["Deni Avdija",['SG', 'SF', 'PF'],"POR"],
["Onyeka Okongwu",['C'],"ATL"],["Trae Young",['PG'],"WAS"],["Kon Knueppel",['SG', 'SF'],"CHA"],
["Brandon Miller",['SF', 'PF'],"CHA"],["LeBron James",['SF', 'PF'],"PHI"],["Kyrie Irving",['PG'],"DAL"],
["Domantas Sabonis",['C', 'PF'],"SAC"],["Keyonte George",['PG', 'SG'],"UTA"],["OG Anunoby",['SF', 'PF'],"NY"],
["Anthony Davis",['C', 'PF'],"WAS"],["Paolo Banchero",['PF'],"ORL"],["Jaren Jackson Jr.",['C', 'PF'],"UTA"],
["Dyson Daniels",['SG', 'SF'],"ATL"],["Cameron Boozer",['PF'],"MEM"],["Kel'el Ware",['C'],"MIL"],
["Michael Porter Jr.",['SF', 'PF'],"BKN"],["Walker Kessler",['C'],"LAL"],["Joel Embiid",['C'],"PHI"],
["Jalen Williams",['SF', 'PF'],"OKC"],["Matas Buzelis",['SF', 'PF'],"CHI"],["Ryan Rollins",['PG', 'SG'],"MIL"],
["Mikal Bridges",['SF', 'PF'],"NY"],["Julius Randle",['PF'],"BKN"],["Naz Reid",['C', 'PF'],"CHA"],
["Payton Pritchard",['PG'],"BOS"],["VJ Edgecombe",['PG', 'SG'],"PHI"],["Brandon Ingram",['SG', 'SF', 'PF'],"LAC"],
["Pascal Siakam",['PF', 'C'],"IND"],["De'Aaron Fox",['PG'],"SA"],["Alex Sarr",['C'],"WAS"],
["Rudy Gobert",['C'],"MIN"],["Jaden McDaniels",['SF'],"MIN"],["Damian Lillard",['PG'],"POR"],
["Immanuel Quickley",['PG', 'SG'],"TOR"],["Jarrett Allen",['C'],"CLE"],["Franz Wagner",['SF', 'PF'],"ORL"],
["Darius Garland",['PG'],"LAC"],["Stephon Castle",['PG', 'SG'],"SA"],["Tyler Herro",['PG', 'SG'],"MIL"],
["Dejounte Murray",['PG'],"NO"],["Jabari Smith Jr.",['PF', 'C'],"HOU"],["Andrew Wiggins",['SG', 'SF', 'PF'],"MIA"],
["Ivica Zubac",['C'],"IND"],["Caleb Wilson",['PF'],"CHI"],["Paul George",['SF', 'PF'],"BOS"],
["Norman Powell",['SG', 'SF'],"CHI"],["Zion Williamson",['PF', 'C'],"NO"],["Myles Turner",['C'],"MIL"],
["Neemias Queta",['C'],"BOS"],["AJ Dybantsa",['SF'],"WAS"],["Josh Hart",['SF', 'SG'],"NY"],
["Ausar Thompson",['SG', 'SF', 'PF'],"DET"],["Zach Edey",['C'],"MEM"],["Miles Bridges",['PF'],"PHO"],
["Derik Queen",['PF', 'C'],"NO"],["Kevin Porter Jr.",['PG', 'SG'],"MIL"],["Ayo Dosunmu",['SG', 'PG'],"MIN"],
["Jalen Suggs",['PG', 'SG'],"ORL"],["Reed Sheppard",['PG', 'SG'],"HOU"],["Cason Wallace",['PG', 'SG', 'SF'],"OKC"],
["DeMar DeRozan",['SF', 'PF'],"DEN"],["Kristaps Porzingis",['C'],"GS"],["CJ McCollum",['PG', 'SG'],"ATL"],
["John Collins",['PF', 'C'],"DET"],["Dylan Harper",['PG', 'SG'],"SA"],["Coby White",['PG', 'SG'],"CHA"],
["Toumani Camara",['SF', 'PF'],"POR"],["Ja Morant",['PG'],"POR"],["Darryn Peterson",['SG'],"UTA"],
["Ty Jerome",['PG', 'SG'],"MEM"],["Brandin Podziemski",['SG', 'PG'],"GS"],["Nic Claxton",['C'],"CHI"],
["Saddiq Bey",['SF', 'PF'],"NO"],["Isaiah Hartenstein",['C'],"OKC"],["Cedric Coward",['SG', 'SF'],"MEM"],
["Ajay Mitchell",['PG', 'SG'],"OKC"],["Fred VanVleet",['PG'],"HOU"],["Julian Champagnie",['SF', 'PF'],"SA"],
["Collin Gillespie",['PG', 'SG'],"PHO"],["Zach LaVine",['PG', 'SG', 'SF'],"SAC"],["Day'Ron Sharpe",['C'],"BKN"],
["Sandro Mamukelashvili",['PF', 'C'],"LAL"],["Peyton Watson",['SF', 'PF'],"CLE"],["Kyshawn George",['SG', 'SF', 'PF'],"WAS"],
["Deandre Ayton",['C'],"WAS"],["Darius Acuff Jr.",['PG'],"SAC"],["Keegan Murray",['PF', 'SF'],"SAC"],
["Tre Jones",['PG', 'SG'],"CHI"],["Mark Williams",['C'],"PHO"],["Andrew Nembhard",['PG', 'SG'],"IND"],
["Nikola Vucevic",['C'],"ORL"],["Jaime Jaquez Jr.",['SG', 'SF', 'PF'],"MIL"],["Grayson Allen",['SG', 'SF'],"CHA"],
["Maxime Raynaud",['C'],"SAC"],["Devin Vassell",['SG', 'SF'],"SA"],["Anthony Black",['PG', 'SG', 'SF'],"ORL"],
["Moussa Diabate",['C'],"CHA"],["Collin Murray-Boyles",['PF', 'C'],"TOR"],["Jakob Poeltl",['C'],"TOR"],
["RJ Barrett",['SG', 'SF', 'PF'],"TOR"],["Jalen Green",['SG', 'SF'],"PHO"],["Wendell Carter Jr.",['C'],"ORL"],
["Bobby Portis",['PF', 'C'],"MIA"],["Jusuf Nurkic",['C'],"UTA"],["Kyle Filipowski",['C', 'PF'],"UTA"],
["P.J. Washington",['PF', 'C'],"DAL"],["Aday Mara",['C'],"OKC"],["Jrue Holiday",['PG', 'SG'],"POR"],
["Kelly Oubre Jr.",['SF', 'PF'],"IND"],["Isaiah Stewart",['C', 'PF'],"MEM"],["Al Horford",['PF', 'C'],"GS"],
["Mitchell Robinson",['C'],"BOS"],["Ace Bailey",['SF', 'PF'],"UTA"],["Collin Sexton",['PG', 'SG'],"LAL"],
["Aaron Gordon",['PF', 'C'],"DEN"],["Bennedict Mathurin",['SG', 'SF'],"NO"],["Jerami Grant",['PF', 'SF'],"MEM"],
["Brook Lopez",['C'],"LAC"],["Tari Eason",['SG', 'SF', 'PF'],"HOU"],["Jimmy Butler",['SF', 'PF'],"GS"],
["Quentin Grimes",['SG', 'SF'],"LAL"],["Jeremiah Fears",['PG', 'SG'],"NO"],["Davion Mitchell",['PG'],"MIA"],
["Tobias Harris",['PF'],"SA"],["Yaxel Lendeborg",['PF'],"GS"],["Morez Johnson Jr.",['PF'],"DAL"],
["Paul Reed",['PF', 'C'],"DET"],["Egor Demin",['PG', 'SG'],"BKN"],["Keaton Wagler",['SG'],"LAC"],
["Dillon Brooks",['SF', 'PF'],"PHO"],["Luke Kennard",['SG', 'SF'],"PHO"],["Daniel Gafford",['C'],"DAL"],
["Cam Johnson",['SF', 'PF'],"DEN"],["Mikel Brown Jr.",['PG'],"BKN"],["Draymond Green",['PF', 'C'],"GS"],
["Alex Caruso",['SG', 'SF'],"OKC"],["Andre Drummond",['C'],"NY"],["AJ Green",['PG', 'SG', 'SF'],"MIL"],
["Klay Thompson",['SG', 'SF'],"MIA"],["Aaron Wiggins",['SG', 'SF'],"ATL"],["Aaron Nesmith",['SG', 'SF'],"IND"],
["Anfernee Simons",['PG', 'SG'],"PHI"],["Jared McCain",['PG', 'SG'],"OKC"],["Christian Braun",['SG', 'SF', 'PF'],"DEN"],
["Rui Hachimura",['PF', 'SF'],"LAC"],["Jonathan Kuminga",['SF', 'PF'],"MIN"],["Kyle Kuzma",['PF', 'SF'],"MIL"],
["Khaman Maluach",['C'],"PHO"],["Pelle Larsson",['SG', 'SF'],"MIA"],["Scotty Pippen Jr.",['PG'],"MEM"],
["Shaedon Sharpe",['PG', 'SG'],"POR"],["Herbert Jones",['SG', 'SF'],"NO"],["Bilal Coulibaly",['SG', 'SF'],"WAS"],
["Dereck Lively II",['C'],"DAL"],["Scoot Henderson",['PG'],"POR"],["Naji Marshall",['SG', 'SF', 'PF'],"DAL"],
["Jay Huff",['C'],"IND"],["Yves Missi",['C'],"NO"],["Santi Aldama",['PF'],"DAL"],
["Keon Ellis",['SG', 'SF'],"BKN"],["Max Christie",['SG', 'SF'],"DAL"],["Ryan Kalkbrenner",['C'],"CHA"],
["Isaiah Joe",['SG', 'SF'],"DET"],["Isaiah Collier",['PG', 'SG'],"UTA"],["De'Andre Hunter",['SF', 'PF'],"SAC"],
["Duncan Robinson",['SG', 'SF'],"DET"],["Sam Merrill",['SG', 'SF'],"CLE"],["Keldon Johnson",['SF', 'PF'],"SA"],
["Ja'Kobe Walter",['PG', 'SG'],"TOR"],["Kingston Flemings",['PG'],"ATL"],["Ron Holland",['SF', 'PF'],"DET"],
["Jaylen Wells",['SG', 'SF'],"MEM"],["Malik Monk",['SG', 'PG'],"SAC"],["Bub Carrington",['PG', 'SG'],"WAS"],
["Allen Graves",['PF'],"TOR"],["T.J. McConnell",['PG'],"IND"],["Brice Sensabaugh",['SG', 'SF', 'PF'],"UTA"],
["Derrick Jones Jr.",['SF', 'PF'],"LAC"],["GG Jackson",['SF', 'PF', 'C'],"MEM"],["Adem Bona",['C'],"PHI"],
["Dennis Schroder",['PG', 'SG'],"CHA"],["Miles McBride",['PG', 'SG'],"NY"],["Steven Adams",['C'],"HOU"],
["Taylor Hendricks",['PF', 'C'],"MEM"],["Walter Clayton Jr.",['PG', 'SG'],"MEM"],["Jalen Smith",['C', 'PF'],"CHI"],
["Obi Toppin",['SF', 'PF'],"IND"],["Jamal Shead",['PG'],"TOR"],["Royce O'Neale",['SF', 'PF'],"CHA"],
["Luke Kornet",['C'],"SA"],["Luguentz Dort",['SG', 'SF'],"ATL"],["Leonard Miller",['SF', 'PF'],"CHI"],
["Nate Ament",['SF'],"MIL"],["Sam Hauser",['SF', 'PF'],"BOS"],["Gradey Dick",['SG', 'SF'],"LAC"],
["Jose Alvarado",['PG'],"NY"],["Tristan da Silva",['SF', 'PF'],"ORL"],["Harrison Barnes",['PF'],"SA"],
["Goga Bitadze",['C'],"ORL"],["Khris Middleton",['SF', 'PF'],"WAS"],["Nikola Jovic",['PF', 'C'],"MIA"],
["Yang Hansen",['C'],"POR"],["Donte DiVincenzo",['SG', 'PG'],"MIN"],["Moses Moody",['SG', 'SF', 'PF'],"GS"],
["Jonas Valanciunas",['C'],"DEN"],["Clint Capela",['C'],"HOU"],["Nicolas Batum",['PF'],"LAC"],
["Jarred Vanderbilt",['PF', 'C'],"LAL"],["Jordan Clarkson",['SG', 'SF'],"NY"],["Jaden Ivey",['SG', 'PG'],"DET"],
["Aaron Holiday",['PG'],"HOU"],["Rob Dillingham",['PG', 'SG'],"CHA"],["Jeremy Sochan",['PF', 'C'],"POR"],
["Taurean Prince",['SF', 'PF'],"DET"],["Tristan Vukcevic",['C'],"WAS"],["Caris LeVert",['SG', 'SF'],"MIL"],
["Buddy Hield",['SG', 'SF'],"CHI"],["Thomas Bryant",['C'],"CLE"],["Mike Conley",['PG'],"BOS"],
["Haywood Highsmith",['SF'],"MIA"],["Kevon Looney",['PF', 'C'],"LAL"],["Cam Whitmore",['SF', 'PF'],"DEN"],
["Devin Carter",['PG', 'SG'],"BOS"],["Kenrich Williams",['PF', 'C'],"OKC"],["Ochai Agbaji",['SF', 'SG'],"TOR"],
["Bogdan Bogdanovic",['PG', 'SG', 'SF'],"HOU"],["D'Angelo Russell",['PG', 'SG'],"DAL"],["Cam Thomas",['SG'],"BKN"],
["Jonathan Isaac",['PF', 'C'],"ORL"],["Dorian Finney-Smith",['PF', 'SF'],"ATL"],["Jonathan Mogbo",['PF'],"TOR"]

];
PLAYERS.forEach(function(p,i){p.r=i+1;p.n=p[0];p.p=p[1];p.t=p[2]||"\u2014";});
PLAYERS.forEach(function(p){var d=(typeof PDATA!=="undefined"&&PDATA[p.n])||null;p.adp=d&&d.adp!=null?d.adp:null;p.adpF=d&&d.adpF!=null?d.adpF:null;p.last=d&&d.last!=null?d.last:null;p.lastTotal=d&&d.lastTotal!=null?d.lastTotal:null;p.mpg=d&&d.mpg!=null?d.mpg:null;p.inj=(typeof INJ!=="undefined"&&INJ[p.n])||null;p.teamPrev=d&&d.teamPrev||null;p.teamCurr=(d&&d.teamCurr)||p.t;p.mover=!!(d&&d.mover);p.roleDelta=(d&&d.roleDelta)||"unknown";p.roleNote=(d&&d.roleNote)||null;p.projMpg=d&&d.projMpg!=null?d.projMpg:null;p.projRank=d&&d.projRank!=null?d.projRank:null;p.vacatedGainers=(d&&d.vacatedGainers)||null;});
/* Category strength tags: derived from 2025-26 per-game category values (cv).
   Top 4 categories with cv > 0, in descending order. The 8 entries below are a
   manual fallback for players with no 2025-26 data (injured stars + prospects
   scouted without NBA production); the last 4 prospects have no tags. */
var CATS={
"Tyrese Haliburton":["AST","STL","3PM","FT%"],
"Kyrie Irving":["PTS","AST","3PM","FT%"],
"Fred VanVleet":["AST","STL","3PM"],
"AJ Dybantsa":["PTS"],
"Darryn Peterson":["PTS"],
"Cameron Boozer":["PTS","REB"],
"Caleb Wilson":["PTS","REB"],
"Darius Acuff Jr.":["AST"],
"Nikola Jokic":["AST","REB","FG%","PTS"],
"Victor Wembanyama":["BLK","REB","PTS","FG%"],
"Shai Gilgeous-Alexander":["FT%","PTS","FG%","AST"],
"Luka Doncic":["PTS","3PM","AST","STL"],
"Tyrese Maxey":["STL","PTS","FT%","3PM"],
"Cade Cunningham":["AST","PTS","STL","BLK"],
"Giannis Antetokounmpo":["FG%","PTS","REB","AST"],
"Jalen Johnson":["AST","REB","PTS","STL"],
"Donovan Mitchell":["PTS","3PM","FT%","STL"],
"Anthony Edwards":["PTS","3PM","STL","BLK"],
"Cooper Flagg":["PTS","STL","BLK","REB"],
"Jayson Tatum":["REB","3PM","STL","PTS"],
"Amen Thompson":["STL","FG%","REB","AST"],
"Scottie Barnes":["BLK","STL","AST","REB"],
"Jamal Murray":["AST","3PM","PTS","FT%"],
"Alperen Sengun":["REB","AST","FG%","BLK"],
"Karl-Anthony Towns":["REB","FT%","PTS","FG%"],
"Kevin Durant":["PTS","FT%","FG%","3PM"],
"Mikal Bridges":["STL","TO","3PM","BLK"],
"James Harden":["FT%","AST","3PM","PTS"],
"Jaylen Brown":["PTS","AST","REB","3PM"],
"Chet Holmgren":["BLK","REB","FG%","PTS"],
"Kawhi Leonard":["STL","FT%","PTS","3PM"],
"Jalen Duren":["FG%","REB","PTS","BLK"],
"Evan Mobley":["BLK","REB","FG%","PTS"],
"Deni Avdija":["AST","PTS","REB","FT%"],
"Devin Booker":["FT%","PTS","AST","3PM"],
"Pascal Siakam":["PTS","REB","STL","AST"],
"Paolo Banchero":["REB","PTS","AST"],
"Trey Murphy III":["3PM","STL","FT%","PTS"],
"Stephon Castle":["AST","STL","PTS","REB"],
"Kon Knueppel":["3PM","PTS","FT%","REB"],
"Josh Giddey":["AST","REB","PTS","3PM"],
"VJ Edgecombe":["STL","3PM","AST","PTS"],
"Jalen Brunson":["PTS","AST","3PM","FT%"],
"Austin Reaves":["FT%","PTS","AST","3PM"],
"Jalen Williams":["AST","STL","FT%","PTS"],
"Darius Garland":["AST","3PM","PTS","FT%"],
"Domantas Sabonis":["REB","FG%","AST","PTS"],
"Keyonte George":["FT%","PTS","AST","3PM"],
"Anthony Davis":["REB","BLK","PTS","FG%"],
"Lauri Markkanen":["FT%","PTS","3PM","REB"],
"LeBron James":["AST","PTS","FG%","STL"],
"Paul George":["STL","3PM","PTS","FT%"],
"Dejounte Murray":["STL","AST","FT%","PTS"],
"Michael Porter Jr.":["3PM","PTS","FT%","REB"],
"Matas Buzelis":["BLK","3PM","REB","PTS"],
"Ja Morant":["AST","FT%","PTS","STL"],
"Brandon Miller":["3PM","FT%","PTS","STL"],
"Trae Young":["AST","FT%","PTS","3PM"],
"Nickeil Alexander-Walker":["3PM","FT%","STL","PTS"],
"Alex Sarr":["BLK","REB","PTS","FG%"],
"Stephen Curry":["3PM","FT%","PTS","AST"],
"Zion Williamson":["FG%","PTS","REB","STL"],
"Jaren Jackson Jr.":["BLK","PTS","STL","3PM"],
"LaMelo Ball":["3PM","AST","PTS","FT%"],
"Bam Adebayo":["REB","PTS","STL","3PM"],
"De'Aaron Fox":["AST","STL","PTS","3PM"],
"Desmond Bane":["FT%","PTS","3PM","AST"],
"Franz Wagner":["PTS","FT%","FG%","STL"],
"Derrick White":["BLK","3PM","AST","FT%"],
"Joel Embiid":["FT%","PTS","BLK","REB"],
"Devin Vassell":["3PM","TO","FT%"],
"Tyler Herro":["FT%","3PM","PTS","AST"],
"Rudy Gobert":["REB","BLK","FG%","TO"],
"Myles Turner":["BLK","TO","3PM","REB"],
"Jarrett Allen":["FG%","REB","BLK","TO"],
"Deandre Ayton":["FG%","REB","BLK","TO"],
"Ivica Zubac":["REB","FG%","BLK"],
"Nic Claxton":["FG%","BLK","REB","TO"],
"Walker Kessler":["FG%","BLK","REB","STL"],
"Mark Williams":["FG%","REB","BLK","TO"],
"Onyeka Okongwu":["BLK","REB","STL","3PM"],
"Naz Reid":["BLK","3PM","REB","STL"],
"Julius Randle":["PTS","AST","REB","STL"],
"Derik Queen":["REB","BLK","STL","AST"],
"Aaron Gordon":["TO","FG%","REB","PTS"],
"Jabari Smith Jr.":["3PM","BLK","REB","TO"],
"Keegan Murray":["BLK","TO","STL","REB"],
"Tari Eason":["STL","REB","TO","3PM"],
"Luguentz Dort":["TO","3PM"],
"Alex Caruso":["STL","TO"],
"Dyson Daniels":["STL","AST","REB","FG%"],
"Jalen Suggs":["STL","AST","3PM","FT%"],
"Anfernee Simons":["3PM","TO","FT%"],
"Coby White":["3PM","PTS","FT%","AST"],
"Immanuel Quickley":["AST","STL","3PM","PTS"],
"Scoot Henderson":["FT%","3PM","AST"],
"Reed Sheppard":["STL","3PM","TO","BLK"],
"Jared McCain":["TO","FT%"],
"Brandin Podziemski":["STL","3PM","AST","TO"],
"Malik Monk":["3PM","FT%","TO"],
"Cam Thomas":["FT%"],
"Norman Powell":["3PM","PTS","FT%","STL"],
"OG Anunoby":["STL","3PM","FT%","PTS"],
"Miles Bridges":["3PM","PTS","TO","REB"],
"Andrew Wiggins":["BLK","STL","3PM","TO"],
"Jimmy Butler":["FT%","STL","PTS","FG%"],
"Brandon Ingram":["PTS","FT%","BLK","3PM"],
"DeMar DeRozan":["FT%","PTS","TO","AST"],
"Khris Middleton":["FT%"],
"Tobias Harris":["TO","FT%","REB","STL"],
"Jerami Grant":["3PM","PTS","FT%","BLK"],
"Kyle Kuzma":["FG%"],
"Keldon Johnson":["TO","FG%","REB"],
"Jeremy Sochan":["TO","FG%"],
"Harrison Barnes":["TO","3PM","FT%"],
"Cam Johnson":["TO","3PM","FT%","FG%"],
"Dillon Brooks":["PTS","3PM","FT%","STL"],
"Aaron Wiggins":["TO","STL"],
"Isaiah Joe":["TO","3PM","FT%"],
"Jaime Jaquez Jr.":["AST","FG%","PTS"],
"Nikola Jovic":["TO"],
"Kel'el Ware":["REB","BLK","TO","FG%"],
"Kristaps Porzingis":["BLK","FT%","TO","PTS"],
"Bobby Portis":["TO","REB","3PM","FG%"],
"Clint Capela":["TO","BLK","FG%"],
"Nikola Vucevic":["REB","TO","FG%","BLK"],
"Jonas Valanciunas":["FG%","TO","REB","BLK"],
"Jusuf Nurkic":["REB","STL","AST","FG%"],
"Brook Lopez":["BLK","TO","3PM"],
"Daniel Gafford":["FG%","BLK","REB","TO"],
"Dereck Lively II":["BLK","FG%","TO","REB"],
"Isaiah Stewart":["BLK","FG%","TO"],
"Jalen Smith":["TO","REB","BLK","3PM"],
"Jalen Green":["3PM","PTS","STL"],
"Zach LaVine":["3PM","FT%","PTS","FG%"],
"Bennedict Mathurin":["FT%","PTS","REB"],
"Shaedon Sharpe":["STL","PTS","3PM"],
"Anthony Black":["STL","BLK","AST","PTS"],
"Payton Pritchard":["3PM","AST","FT%","PTS"],
"Quentin Grimes":["FT%","3PM","AST"],
"Grayson Allen":["3PM","STL","FT%","PTS"],
"Sam Merrill":["3PM","TO","FT%"],
"Ayo Dosunmu":["FG%","FT%","TO","3PM"],
"Donte DiVincenzo":["3PM","STL","TO","AST"],
"Josh Hart":["REB","AST","STL","FG%"],
"De'Andre Hunter":["FT%","3PM","TO"],
"Toumani Camara":["3PM","STL","REB"],
"Royce O'Neale":["3PM","STL","TO"],
"Saddiq Bey":["TO","FT%","3PM","PTS"],
"Herbert Jones":["STL","TO"],
"Jaylen Wells":["TO","3PM"],
"Naji Marshall":["FG%","STL","PTS","TO"],
"Klay Thompson":["3PM","TO"],
"P.J. Washington":["BLK","REB","STL"],
"John Collins":["FG%","BLK","TO","REB"],
"Santi Aldama":["REB","TO","BLK","3PM"],
"Jonathan Isaac":["TO","BLK"],
"Wendell Carter Jr.":["REB","TO","FG%","BLK"],
"Goga Bitadze":["TO","FG%","BLK"],
"Mitchell Robinson":["REB","FG%","BLK","TO"],
"Isaiah Hartenstein":["REB","FG%","BLK","STL"],
"Yves Missi":["BLK","TO","FG%","REB"],
"Zach Edey":["BLK","REB","FG%"],
"Donovan Clingan":["REB","BLK","FG%","TO"],
"Steven Adams":["REB","TO","BLK","FG%"],
"Kevon Looney":["TO","REB"],
"Jakob Poeltl":["FG%","REB","TO","BLK"],
"Ace Bailey":["3PM","BLK","TO"],
"Dylan Harper":["FG%","AST","TO"],
"Rob Dillingham":["TO"],
"Isaiah Collier":["AST","STL","FG%"],
"Walter Clayton Jr.":["FT%","AST"],
"T.J. McConnell":["AST","FG%","TO","STL"],
"Andrew Nembhard":["AST","FT%","PTS","3PM"],
"Dennis Schroder":["AST","FT%"],
"Scotty Pippen Jr.":["STL","AST"],
"Mike Conley":["TO","FT%"],
"Tre Jones":["FG%","AST","STL","FT%"],
"Davion Mitchell":["AST","STL","TO","FG%"],
"Jose Alvarado":["TO","STL","AST"],
"Jeremiah Fears":["STL","AST"],
"Collin Gillespie":["3PM","STL","AST","FT%"],
"Jamal Shead":["AST","TO","STL"],
"Bub Carrington":["AST","3PM"],
"Miles McBride":["3PM","TO"],
"Ryan Rollins":["STL","AST","3PM","PTS"],
"Aaron Holiday":["TO","FT%"],
"Devin Carter":["TO"],
"Keon Ellis":["TO","STL","BLK"],
"Cason Wallace":["STL","TO"],
"Moses Moody":["3PM","TO","STL"],
"D'Angelo Russell":["AST"],
"Jordan Clarkson":["TO","FT%"],
"Buddy Hield":["TO"],
"Caris LeVert":["TO","BLK"],
"Bogdan Bogdanovic":["TO"],
"Max Christie":["3PM","FT%","TO"],
"Gradey Dick":["TO","FT%"],
"RJ Barrett":["PTS","FG%","3PM","REB"],
"Jaden Ivey":["TO"],
"Ochai Agbaji":["TO","FT%"],
"Ausar Thompson":["STL","BLK","FG%","REB"],
"Ron Holland":["STL","TO","FT%"],
"Bilal Coulibaly":["STL","BLK","TO"],
"Kyshawn George":["BLK","AST","3PM","STL"],
"Cam Whitmore":["TO"],
"Tristan da Silva":["TO","FT%","3PM"],
"Ja'Kobe Walter":["TO","STL","3PM"],
"Pelle Larsson":["TO","FG%","AST","FT%"],
"Haywood Highsmith":["TO","FG%","FT%"],
"Derrick Jones Jr.":["TO","BLK","FG%"],
"Taurean Prince":["3PM","TO","FT%"],
"Aaron Nesmith":["3PM","TO","FT%"],
"Obi Toppin":["FT%","TO","FG%","3PM"],
"Taylor Hendricks":["TO"],
"Kyle Filipowski":["REB","FG%","STL","TO"],
"Brice Sensabaugh":["3PM","FT%","PTS","TO"],
"Jonathan Mogbo":["TO","FG%"],
"Collin Murray-Boyles":["FG%","TO","BLK","STL"],
"GG Jackson":["BLK","FG%","TO"],
"Leonard Miller":["TO","FG%"],
"Dorian Finney-Smith":["TO"],
"Rui Hachimura":["TO","FG%","3PM"],
"Jarred Vanderbilt":["TO"],
"Nicolas Batum":["TO"],
"Kenrich Williams":["TO"],
"Adem Bona":["BLK","TO","FG%"],
"Tristan Vukcevic":["TO","BLK"],
"Yang Hansen":["TO"],
"Maxime Raynaud":["FG%","REB","TO"],
"Thomas Bryant":["TO","FG%"],
"Luke Kornet":["TO","FG%","BLK","REB"],
"Neemias Queta":["FG%","BLK","REB","TO"],
"Jay Huff":["BLK","TO","FT%"],
"AJ Green":["3PM","TO","FT%"],
"Jaden McDaniels":["BLK","FG%","STL","FT%"],
"Al Horford":["BLK","TO","3PM"],
"Luke Kennard":["TO","FG%","FT%"],
"Andre Drummond":["REB","TO","BLK"],
"Day'Ron Sharpe":["FG%","REB","STL"],
"Moussa Diabate":["REB","FG%","BLK","TO"],
"Ty Jerome":["3PM","AST","FT%","PTS"],
"Duncan Robinson":["3PM","TO"],
"Cedric Coward":["FT%","REB"],
"Sam Hauser":["TO","3PM"],
"Kelly Oubre Jr.":["STL","TO","3PM","REB"],
"CJ McCollum":["3PM","PTS","AST"],
"Ajay Mitchell":["STL","FT%","TO","AST"],
"Draymond Green":["AST","REB","BLK"],
"Ryan Kalkbrenner":["BLK","FG%","TO","REB"],
"Sandro Mamukelashvili":["TO","FG%"],
"Peyton Watson":["BLK","FG%","PTS","STL"],
"Kevin Porter Jr.":["STL","AST","FT%","PTS"],
"Jrue Holiday":["AST","3PM","PTS","STL"],
"Julian Champagnie":["TO","3PM","REB","FT%"],
"Christian Braun":["TO","FG%"],
"Collin Sexton":["FT%","STL","PTS","3PM"],
"Egor Demin":["3PM","FT%","AST","TO"],
"Paul Reed":["FG%","TO","BLK"],
"Jonathan Kuminga":["REB"],
"Khaman Maluach":["TO","BLK","FG%"],
};
PLAYERS.forEach(function(p){p.c=CATS[p.n]||[];});
